### PR TITLE
example: expose function to set plan & query programmatically

### LINKED ISSUE #292: support passing EXPLAIN result & query via location.hash
Thanks for this awesome tool!

I'm trying to automate my PostgreSQL query development workflow by writing [a small CLI helper](https://github.com/derhuerst/pev2-cli) that will open pev2. For this, **there would have to be a way to pass the `EXPLAIN` result & query via the URL** (e.g. `location.hash`).

I'd be happy to submit a PR if you tell me where to but the logic for this!

### PR DESCRIPTION
**Pull request by derhuerst**
Closes #292.

### CODE REVIEW

**Comment by pgiraud** [comment]
Can you please go a step further by changing the following function and use setPlanData there as well?
https://github.com/dalibo/pev2/blob/master/example/src/views/Home.vue#L76-L80

**Comment by derhuerst** [comment]
huh, makes sense to unify it, but calls to global functions are terribly hard to debug/test/etc, so i try to really only use them when necessary. what do you think about `export`ing `setPlanData` and then `import`ing it in `Home.vue`?

**Comment by pgiraud** [comment]
Looks good. Thanks.

**Comment by derhuerst** [comment]
> Can you please go a step further by changing the following function and use `setPlanData` there as well?

FYI I force-pushed my changes.

**Pull request merged**
